### ISSUE TITLE
Installation tutorial? (Docs are preferred..)

### ISSUE THREAD

**Issue by broimsuperman** [ialexpw/Storio#3]
^

**Comment by ialexpw** [comment]
Just saw this so apologies.

Installation is fairly simple, upload the files to your web space with PHP 7.4+. Browse to the location within your browser and it will tell you the folders that need write permissions on them.

I'll add a bit more detail in shortly as I have a few updates planned at the moment. 😄

**Comment by ialexpw** [comment]
Installation is automated - if any issues, messages are shown to guide the installation.

Further documentation will be added later.
